package com.nature.demo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nature.demo.utils.db.BaseReferInfo;

import com.nature.demo.dao.BaseReferInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseReferInfoDaoConfig;

    private final BaseReferInfoDao baseReferInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseReferInfoDaoConfig = daoConfigMap.get(BaseReferInfoDao.class).clone();
        baseReferInfoDaoConfig.initIdentityScope(type);

        baseReferInfoDao = new BaseReferInfoDao(baseReferInfoDaoConfig, this);

        registerDao(BaseReferInfo.class, baseReferInfoDao);
    }
    
    public void clear() {
        baseReferInfoDaoConfig.clearIdentityScope();
    }

    public BaseReferInfoDao getBaseReferInfoDao() {
        return baseReferInfoDao;
    }

}
