package com.dk.lib_dk.utils.tsp.gcom;

/**
 * @ProjectName: ControlPlatform
 * @Desc:
 * @Author: hq
 * @Date: 2023/4/12
 */
public enum GeoError {

    NOT_KNOW_ERROR(-1, "未知错误"),
    //TPS
    GRC_OK(0, "成功"),
    GRC_UNDEFINED(1, "系统未知错误"),
    GRC_IVPARAM(2, "参数有误"),
    GRC_IVRESULT(3, "无效的结果"),
    GRC_FATAL(4, "致命错误"),
    GRC_NOT_IMPL(5, "尚未就绪"),
    GRC_TIME_OUT(6, "函数执行超时"),
    GRC_SET_INCOMPL(7, "参数设置不完整"),
    GRC_ABORT(8, "测量终止"),
    GRC_NOMEMORY(9, "内存不足"),
    GRC_NOTINIT(10, "系统未初始化"),
    GRC_SHUT_DOWN(12, "系统已关闭"),
    GRC_SYSBUSY(13, "系统在其他进程中使用"),
    GRC_HWFAILURE(14, "致命错误-硬件故障"),
    GRC_ABORT_APPL(15, "程序退出"),
    GRC_LOW_POWER(16, "电量不足"),
    GRC_IVVERSION(17, "文件版本无效"),
    GRC_BATT_EMPTY(18, "电池没电"),
    GRC_NO_EVENT(20, "等待中"),
    GRC_OUT_OF_TEMP(21, "超出温度范围"),
    GRC_INSTRUMENT_TILT(22, "仪器倾斜超出范围"),
    GRC_COM_SETTING(23, "通信故障"),
    GRC_NO_ACTION(24, "命令未执行"),
    GRC_SLEEP_MODE(25, "进入睡眠模式"),
    GRC_NOTOK(26, "功能未成功完成"),
    GRC_NA(27, "无法使用"),
    GRC_OVERFLOW(28, "溢出错误"),
    GRC_STOPPED(29, "系统已停止"),

    //ANG
    GRC_ANG_ERROR(257, "角度和倾角无效"),
    GRC_ANG_INCL_ERROR(258, "倾角无效"),
    GRC_ANG_BAD_ACC(259, "未达到数值精度"),
    GRC_ANG_BAD_ANGLE_ACC(260, "未达到角度精度"),
    GRC_ANG_BAD_INCLIN_ACC(261, "未达到倾斜精度"),
    GRC_ANG_WRITE_PROTECTED(266, "没有写权限"),
    GRC_ANG_OUT_OF_RANGE(267, "值超出范围"),
    GRC_ANG_IR_OCCURED(268, "执行被终止"),
    GRC_ANG_HZ_MOVED(269, "水平角测量期间被移动"),
    GRC_ANG_OS_ERROR(270, "操作系统错误"),
    GRC_ANG_DATA_ERROR(271, "参数值溢出"),
    GRC_ANG_PEAK_CNT_UFL(272, "峰值过少"),
    GRC_ANG_TIME_OUT(273, "读取超时"),
    GRC_ANG_TOO_MANY_EXPOS(274, "光线太强"),
    GRC_ANG_PIX_CTRL_ERR(275, "图片曝光超出范围"),
    GRC_ANG_MAX_POS_SKIP(276, "正面曝光动态溢出"),
    GRC_ANG_MAX_NEG_SKIP(277, "反面曝光动态溢出"),
    GRC_ANG_EXP_LIMIT(278, "曝光时间溢出"),
    GRC_ANG_UNDER_EXPOSURE(279, "图片曝光不足"),
    GRC_ANG_OVER_EXPOSURE(280, "图片曝光过度"),
    GRC_ANG_TMANY_PEAKS(300, "峰值过多"),
    GRC_ANG_TLESS_PEAKS(301, "峰值过少"),
    GRC_ANG_PEAK_TOO_SLIM(302, "峰值过小"),
    GRC_ANG_PEAK_TOO_WIDE(303, "峰值过宽"),
    GRC_ANG_BAD_PEAKDIFF(304, "峰差过大"),
    GRC_ANG_UNDER_EXP_PICT(305, "峰值振幅太小"),
    GRC_ANG_PEAKS_INHOMOGEN(306, "不均匀的峰值振幅"),
    GRC_ANG_NO_DECOD_POSS(307, "无法进行峰值解码"),
    GRC_ANG_UNSTABLE_DECOD(308, "峰值解码不稳定"),
    GRC_ANG_TLESS_FPEAKS(309, "有效峰值太少"),
    GRC_ANG_INCL_OLD_PLANE(316, "倾斜平面超出范围"),
    GRC_ANG_INCL_NO_PLANE(317, "倾斜平面不可用"),
    GRC_ANG_FAST_ANG_ERR(326, "5KHz和2.5Hz角度错误"),
    GRC_ANG_FAST_ANG_ERR_5(327, "5KHz角度有误"),
    GRC_ANG_FAST_ANG_ERR_25(328, "2.5KHz角度有误"),
    GRC_ANG_TRANS_ERR(329, "检测到LVDS传输错误"),
    GRC_ANG_TRANS_ERR_5(330, "在5kHz模式下检测到 LVDS 传输错误"),
    GRC_ANG_TRANS_ERR_25(331, "在2.5kHz模式下检测到 LVDS 传输错误"),

    //ATA
    GRC_ATA_NOT_READY(512, "ATR系统未就绪"),
    GRC_ATA_NO_RESULT(513, "结果尚不可用"),
    GRC_ATA_SEVERAL_TARGETS(514, "检测到多个目标"),
    GRC_ATA_BIG_SPOT(515, "斑点太大，无法分析"),
    GRC_ATA_BACKGROUND(516, "背景太亮"),
    GRC_ATA_NO_TARGETS(517, "未检测到目标"),
    GRC_ATA_NOT_ACCURAT(518, "精度不合格"),
    GRC_ATA_SPOT_ON_EDGE(519, "光点位于感应区域的边缘"),
    GRC_ATA_BLOOMING(522, "检测到边缘溢出或斑点"),
    GRC_ATA_NOT_BUSY(523, "ATR不处于连续模式"),
    GRC_ATA_STRANGE_LIGHT(524, "不是自己的目标照明器的位置"),
    GRC_ATA_V24_FAIL(525, "与传感器ATR的通信错误"),
    GRC_ATA_DECODE_ERROR(526, "接收到的参数无法解码"),
    GRC_ATA_HZ_FAIL(527, "在水平方向未检测到点"),
    GRC_ATA_V_FAIL(528, "在竖直方向未检测到点"),
    GRC_ATA_HZ_STRANGE_L(529, "水平方向光线不稳定"),
    GRC_ATA_V_STRANGE_L(530, "竖直方向光线不稳定"),
    GRC_ATA_SLDR_TRANSFER_PENDING(531, "传输错误"),
    GRC_ATA_SLDR_TRANSFER_ILLEGAL(532, "传输错误"),
    GRC_ATA_SLDR_DATA_ERROR(533, "接受的数据格式有误"),
    GRC_ATA_SLDR_CHK_SUM_ERROR(534, "数据校验出错"),
    GRC_ATA_SLDR_ADDRESS_ERROR(535, "地址超出有效范围"),
    GRC_ATA_SLDR_INV_LOADFILE(536, "固件文件格式无效"),
    GRC_ATA_SLDR_UNSUPPORTED(537, "固件不支持上传"),
    GRC_ATA_PS_NOT_READY(538, "系统未就绪"),
    GRC_ATA_ATR_SYSTEM_ERR(539, "ATR系统错误"),

    //EDM
    GRC_EDM_SYSTEM_ERR(769, "EDM传感器错误"),
    GRC_EDM_INVALID_COMMAND(770, "无效命令或未知命令"),
    GRC_EDM_BOOM_ERR(771, "异常"),
    GRC_EDM_SIGN_LOW_ERR(772, "接收信号偏低，棱镜偏远，或天障、环境恶劣等"),
    GRC_EDM_DIL_ERR(773, "过时的"),
    GRC_EDM_SIGN_HIGH_ERR(774, "接收到的信号过强，棱镜太近"),
    GRC_EDM_TIMEOUT(775, "超出测量时间"),
    GRC_EDM_FLUKT_ERR(776, "异常"),
    GRC_EDM_FMOT_ERR(777, "滤波器故障"),
    GRC_EDM_DEV_NOT_INSTALLED(778, "设备错误"),
    GRC_EDM_NOT_FOUND(779, "搜索结果无效"),
    GRC_EDM_ERROR_RECEIVED(780, "EDM传感器报告错误"),
    GRC_EDM_MISSING_SRVPWD(781, "未设置服务密码"),
    GRC_EDM_INVALID_ANSWER(782, "回复数据有误"),
    GRC_EDM_SEND_ERR(783, "发送缓冲区已满"),
    GRC_EDM_RECEIVE_ERR(784, "数据接收错误"),
    GRC_EDM_INTERNAL_ERR(785, "EDM子系统错误"),
    GRC_EDM_BUSY(786, "电器错误"),
    GRC_EDM_NO_MEASACTIVITY(787, "没有测量"),
    GRC_EDM_CHKSUM_ERR(788, "接收到的数据错误"),
    GRC_EDM_INIT_OR_STOP_ERR(789, "启动或关闭阶段发生错误"),
    GRC_EDM_SRL_NOT_AVAILABLE(790, "此传感器硬件上不提供红色激光"),
    GRC_EDM_MEAS_ABORTED(791, "测量将被中止"),
    GRC_EDM_SLDR_TRANSFER_PENDING(798, "多个传输被调用"),
    GRC_EDM_SLDR_TRANSFER_ILLEGAL(799, "传输错误"),
    GRC_EDM_SLDR_DATA_ERROR(800, "数据格式有误"),
    GRC_EDM_SLDR_CHK_SUM_ERROR(801, "传输数据中的校验和错误"),
    GRC_EDM_SLDR_ADDR_ERROR(802, "地址超出有效范围"),
    GRC_EDM_SLDR_INV_LOADFILE(803, "固件文件格式无效"),
    GRC_EDM_SLDR_UNSUPPORTED(804, "固件不支持上传"),
    GRC_EDM_UNKNOW_ERR(808, "EDM传感器未记录的错误"),
    GRC_EDM_DISTRANGE_ERR(818, "超出距离范围"),
    GRC_EDM_SIGNTONOISE_ERR(819, "信噪比太小"),
    GRC_EDM_NOISEHIGH_ERR(820, "噪声过高"),
    GRC_EDM_PWD_NOTSET(821, "未设置密码"),
    GRC_EDM_ACTION_NO_MORE_VALID(822, "ATR准备和开始快速测量之间经过的时间太长"),
    GRC_EDM_MULTRG_ERR(823, "可能不止一个目标"),
    GRC_EDM_MISSING_EE_CONSTS(824, "常量丢失"),
    GRC_EDM_NOPRECISE(825, "无法精确测量"),
    GRC_EDM_MEAS_DIST_NOT_ALLOWED(826, "测量距离太大"),


    //TMC
    TMC_NO_FULL_CORRECTION(1283, "警告，未完全校正的测量"),
    TMC_ACCURACY_GUARANTEE(1284, "数据存在误差"),
    TMC_ANGLE_OK(1285, "测量数据无效,请检查设备"),
    TMC_ANGLE_NO_FULL_CORRECTION(1288, "警告，仅角度测量有效，精度无法保证"),
    TMC_ANGLE_ACCURACY_GUARANTEE(1289, "数据存在误差"),
    TMC_ANGLE_ERROR(1290, "没有有效的角度测量"),
    TMC_DIST_PPM(1291, "PPM设置错误"),
    TMC_DIST_ERROR(1292, "测距时出错"),
    TMC_BUSY(1293, "TMC被占用"),
    TMC_SIGNAL_ERROR(1294, "错误，EDM上无信号"),

    //MOT
    GRC_MOT_UNREADY(1792, "电机为就绪"),
    GRC_MOT_BUSY(1793, "电机正在处理另一项任务"),
    GRC_MOT_NOT_OCONST(1794, "电机未处于速度模式"),
    GRC_MOT_NOT_CONFIG(1795, "电机模式错误或繁忙"),
    GRC_MOT_NOT_POSIT(1796, "电机未处于定位模式"),
    GRC_MOT_NOT_SERVICE(1797, "电机处于服务模式"),
    GRC_MOT_NOT_BUSY(1798, "电机不处理任何任务"),
    GRC_MOT_NOT_LOCK(1799, "电机未处于跟踪模式"),
    GRC_MOT_NOT_SPIRAL(1800, "电机不是螺旋模式"),
    GRC_MOT_V_ENCODER(1801, "垂直编码器/电机错误"),
    GRC_MOT_HZ_ENCODER(1802, "水平编码器/电机错误"),
    GRC_MOT_HZ_V_ENCODER(1803, "水平和垂直编码器/电机错误"),

    //BMM
    GRC_BMM_XFER_PENDING(2305, "正在打开"),
    GRC_BMM_NO_XFER_OPEN(2306, "传输未打开"),
    GRC_BMM_UNKNOWN_CHARSET(2307, "未知字符集"),
    GRC_BMM_NOT_INSTALLED(2308, "显示模块不存在"),
    GRC_BMM_ALREADY_EXIST(2309, "字符集已经存在"),
    GRC_BMM_CANT_DELETE(2310, "字符集无法删除"),
    GRC_BMM_MEM_ERROR(2311, "无法分配内存"),
    GRC_BMM_CHARSET_USED(2312, "仍在使用的字符集"),
    GRC_BMM_CHARSET_SAVED(2313, "字符集无法删除或受到保护"),
    GRC_BMM_INVALID_ADR(2314, "尝试复制已分配内存之外的字符块"),
    GRC_BMM_CANCELANDADR_ERROR(2315, "释放分配的内存时出错"),
    GRC_BMM_INVALID_SIZE(2316, "标头中指定的字节数与读取的字节数不匹配"),
    GRC_BMM_CANCELANDINVSIZE_ERROR(2317, "分配的内存无法释放"),
    GRC_BMM_ALL_GROUP_OCC(2318, "字符集已满"),
    GRC_BMM_CANT_DEL_LAYERS(2319, "图层无法删除"),
    GRC_BMM_UNKNOWN_LAYER(2320, "所需图层不存在"),
    GRC_BMM_INVALID_LAYERLEN(2321, "图层长度超过最大值"),

    //COM
    GRC_COM_ERO(3072, "启动扩展运行错误"),
    GRC_COM_CANT_ENCODE(3073, "无法对客户端中的参数进行编码"),
    GRC_COM_CANT_DECODE(3074, "无法在客户端解码结果"),
    GRC_COM_CANT_SEND(3075, "发送时出现硬件错误"),
    GRC_COM_CANT_RECV(3076, "接收时出现硬件错误"),
    GRC_COM_TIMEDOUT(3077, "请求超时"),
    GRC_COM_WRONG_FORMAT(3078, "数据包格式错误"),
    GRC_COM_VER_MISMATCH(3079, "客户端和服务器之间的版本不匹配"),
    GRC_COM_CANT_DECODE_REQ(3080, "无法解码服务器中的参数"),
    GRC_COM_PROC_UNAVAIL(3081, "过程ID无效"),
    GRC_COM_CANT_ENCODE_REP(3082, "无法在服务器中对结果进行编码"),
    GRC_COM_SYSTEM_ERR(3083, "未指定的一般系统错误"),
    GRC_COM_FAILED(3085, "未指定的错误"),
    GRC_COM_NO_BINARY(3086, "二进制协议不可用"),
    GRC_COM_INTR(3087, "通话中断"),
    GRC_COM_REQUIRES_8DBITS(3090, "协议需要8位编码字符"),
    GRC_COM_TR_ID_MISMATCH(3093, "ID不匹配错误"),
    GRC_COM_NOT_GEOCOM(3094, "无法识别协议"),
    GRC_COM_UNKNOWN_PORT(3095, "端口地址无效"),
    GRC_COM_ERO_END(3099, "内部错误，数据缓冲区溢出"),
    GRC_COM_OVERRUN(3100, "收到服务器端的无效校验和"),
    GRC_COM_SRVR_RX_CHECKSUM_ERRR(3101, "收到客户端的无效校验和"),
    GRC_COM_CLNT_RX_CHECKSUM_ERRR(3102, "命令有误"),
    GRC_COM_PORT_NOT_AVAILABLE(3103, "端口不可用"),
    GRC_COM_PORT_NOT_OPEN(3104, "无法找到TPS"),
    GRC_COM_NO_PARTNER(3105, "无法启动扩展运行时操作"),
    GRC_COM_ERO_NOT_STARTED(3106, "TPS已经进入休眠状态"),
    GRC_COM_CONS_REQ(3107, "Att to send cons reqs"),
    GRC_COM_SRVR_IS_SLEEPING(3108, "TPS已关闭"),
    GRC_COM_SRVR_IS_OFF(3109, "没有可用的 ASCII 协议校验和"),
    GRC_COM_NO_CHECKSUM(3110, "命令有误"),

    //AUT
    GRC_AUT_TIMEOUT(8704, "未达到位置"),
    GRC_AUT_DETENT_ERROR(8705, "无法定位"),
    GRC_AUT_ANGLE_ERROR(8706, "角度测量错误"),
    GRC_AUT_MOTOR_ERROR(8707, "机械错误"),
    GRC_AUT_INCACC(8708, "未准确到达位置"),
    GRC_AUT_DEV_ERROR(8709, "测量出错"),
    GRC_AUT_NO_TARGET(8710, "未检测到目标"),
    GRC_AUT_MULTIPLE_TARGETS(8711, "检测到多个目标"),
    GRC_AUT_BAD_ENVIRONMENT(8712, "测量环境恶劣"),
    GRC_AUT_DETECTOR_ERROR(8713, "目标获取错误"),
    GRC_AUT_NOT_ENABLED(8714, "ATR模式未启用"),
    GRC_AUT_CALACC(8715, "ATR校准失败"),
    GRC_AUT_ACCURACY(8716, "定位不准确"),
    GRC_AUT_DIST_STARTED(8717, "正在测量"),
    GRC_AUT_SUPPLY_TOO_HIGH(8718, "外部电源电压过高"),
    GRC_AUT_SUPPLY_TOO_LOW(8719, "电源电压太低"),
    GRC_AUT_NO_WORKING_AREA(8720, "未设置工作区"),
    GRC_AUT_ARRAY_FULL(8721, "电力搜索数据阵列已满"),
    GRC_AUT_NO_DATA(8722, "无可用数据"),


    //KDM
    GRC_KDM_NOT_AVAILABLE(12544, "定位不准确"),

    //FTR
    GRC_FTR_FILEACCESS(13056, "定位不准确"),
    GRC_FTR_WRONGFILEBLOCKNUMBER(13057, "定位不准确"),
    GRC_FTR_NOTENOUGHSPACE(13058, "定位不准确"),
    GRC_FTR_INVALIDINPUT(13059, "定位不准确"),
    GRC_FTR_MISSINGSETUP(13060, "定位不准确"),
    ;
    int code;
    String info;

    GeoError(int code, String info) {
        this.code = code;
        this.info = info;
    }

    public static GeoError parse(Integer code) {
        for (GeoError e : GeoError.values()) {
            if (code.equals(e.code)) {
                return e;
            }
        }
        return GeoError.NOT_KNOW_ERROR;
    }

}
